AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Image Generation Application.

Resources:
  DallEApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"

  DallELambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Environment:
        Variables:
          SECRET_NAME: !Ref DallEApiSecret
          BUCKET_NAME: !Ref DallES3Bucket
      Events:
        DallE:
          Type: Api
          Properties:
            Path: /dall-e
            Method: post
            RestApiId: !Ref DallEApi

  DallES3Bucket:
    Type: AWS::S3::Bucket

  DallEApiSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: dall-e-api-secret
      SecretString: YOUR_SECRET_STRING

  DallEDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DallEImages
      AttributeDefinitions:
        - AttributeName: prompt
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: prompt
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${DallEApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/dall-e"
